#!/bin/sh

### BEGIN INIT INFO
# Provides:          9590
# Required-Start:
# Required-Stop:     
# Should-Stop:       
# X-Start-Before:    checkroot
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: A null task to listen on port 9590 (for Nagios testing)
# Description:       
### END INIT INFO

set -e

case "${1:-}" in
  stop|reload|restart|force-reload)
        echo "Stopping 9590."
        /usr/local/share/nems/nems-scripts/9590.sh stop ;;

  start)
        echo "Starting 9590."
        /usr/local/share/nems/nems-scripts/9590.sh start $FORCE ;;

  *)
        echo "Usage: ${0:-} {start|stop|status|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac
