#!/usr/bin/env php
<?php

/*

  check_dhtxx - Version 1.0
  Written by Robbie Ferguson for NEMS Linux
  -----
  1.0 - August 20, 2020 - Initial release

*/

  $dht = json_decode(shell_exec('/usr/local/bin/nems-info dht11 > /dev/null 2>&1'));
  if (!isset($dht->c)) {
    echo 'UNKNOWN - DHT Sensor disconnected or not present.';
    exit(3);
  }
  if ($dht->c == 1 && $dht->h == 1) {
    $dht = json_decode(shell_exec('/usr/local/bin/nems-info dht22 > /dev/null 2>&1'));
  }

  $json = json_encode(array(
      'output' => array(
        'temperature' => $dht->c,
        'humidity' => $dht->h
      ),
      'sensors' => array(
        'temperature' => $dht->c,
        'humidity' => $dht->h
      )
    )
  );  
#  $values = $dht->c . '°C / ' . $dht->f . '°F, ' . $dht->h . '% Humidity';

  if (count($argv) >=5) {
    array_shift($argv);
    $data['crit_low'] = intval(array_shift($argv));
    $data['warn_low'] = intval(array_shift($argv));
    $data['warn_high'] = intval(array_shift($argv));
    $data['crit_high'] = intval(array_shift($argv));
    $data['type'] = (strtolower(array_shift($argv)) ?: 'temp');

    if ($data['warn_high'] > 59) {
      // Over 59 Degrees: we're working in Fahrenheit
      $type = 'F';
    } else {
      $type = 'C';
    }
  } else {
    echo 'NEMS Linux DHTxx Check' . PHP_EOL;
    echo PHP_EOL . 'Usage:                 ' . $argv[0] . ' crit_low warn_low warn_high crit_high [temp|hum]' . PHP_EOL;
    echo 'Example (Temperature): ' . $argv[0] . ' 10 20 39 45 temp' . PHP_EOL;
    echo 'Example (Humidity):    ' . $argv[0] . ' 20 35 65 80 hum' . PHP_EOL;
    echo PHP_EOL . 'For backward compatibility, if type is not specified, temp is assumed.' . PHP_EOL;
    exit(3);
  }

  $tmp = (array) json_decode($json);
  if (is_array($tmp) && isset($tmp['sensors'])) {
    $temper = $tmp;unset ($tmp);
    $data['temperature']['C'] = round($temper->{"internal temperature"},1);
    $data['temperature']['F'] = round(($data['temperature']['C'] * 1.8 + 32),1);

    if ($data['type'] == 'hum' && !isset($temper->{"internal humidity"})) {
      echo 'UNKNOWN - Your TEMPer device does not have a humidity sensor.';
      exit(3);
    } else {
      $data['humidity'] = round($temper->{"internal humidity"},1);
    }

    if ($data['type'] == 'temp') {
      if ($data['temperature'][$type] < $data['crit_low']) {
        echo 'CRITICAL - ' . $data['temperature']['C'] . '°C / ' . $data['temperature']['F'] . '°F (LOW)';
        exit(2);
      } elseif ($data['temperature'][$type] < $data['warn_low']) {
        echo 'WARNING - ' . $data['temperature']['C'] . '°C / ' . $data['temperature']['F'] . '°F (LOW)';
        exit(1);
      } elseif ($data['temperature'][$type] > $data['crit_high']) {
        echo 'CRITICAL - ' . $data['temperature']['C'] . '°C / ' . $data['temperature']['F'] . '°F (HIGH)';
        exit(2);
      } elseif ($data['temperature'][$type] > $data['warn_high']) {
        echo 'WARNING - ' . $data['temperature']['C'] . '°C / ' . $data['temperature']['F'] . '°F (HIGH)'; 
        exit(1);
      } else {
        echo 'OK - ' . $data['temperature']['C'] . '°C / ' . $data['temperature']['F'] . '°F'; 
        exit(0);
      }
    } elseif ($data['type'] == 'hum') {
      if ($data['humidity'] < $data['crit_low']) {
        echo 'CRITICAL - Humidity at ' . $data['humidity'] . '% (LOW)';
        exit(2);
      } elseif ($data['humidity'] < $data['warn_low']) {
        echo 'WARNING - Humidity at ' . $data['humidity'] . '% (LOW)';
        exit(1);
      } elseif ($data['humidity'] > $data['crit_high']) {
        echo 'CRITICAL - Humidity at ' . $data['humidity'] . '% (HIGH)';
        exit(2);
      } elseif ($data['humidity'] > $data['warn_high']) {
        echo 'WARNING - Humidity at ' . $data['humidity'] . '% (HIGH)'; 
        exit(1);
      } else {
        echo 'OK - Humidity at ' . $data['humidity'] . '%'; 
        exit(0);
      }
    } else {
      echo 'UNKNOWN - Invalid command type. Options are temp (temperature) or hum (humidity).';
      exit(3);
    }
  } else {
    echo 'UNKNOWN - TEMPer device disconnected or not present.';
    exit(3);
  }

  
?>
