#!/usr/bin/php
<?php
  // This script is used to reconcile the settings for default NEMS Nagios configs with your NEMS-Migrator backup.
  // We'll take care of the commands / services / hosts configs, but will leave users as is so we don't clobber the nems-init account data

  // Files relative to /etc/nagios3/ and /tmp/nems_migrator_restore/etc/nagios3/ and /root/nems/nems-migrator/data/nagios/
  $files = array(
    array('file'=>'Default_collector/advanced_services.cfg','unique'=>'service_description'),
    array('file'=>'Default_collector/hostgroups.cfg','unique'=>'hostgroup_name'),
    array('file'=>'Default_collector/hosts.cfg','unique'=>'host_name'),
    array('file'=>'Default_collector/servicegroups.cfg','unique'=>'servicegroup_name'),
    array('file'=>'Default_collector/services.cfg','unique'=>'service_description'),
    array('file'=>'global/checkcommands.cfg','unique'=>'command_name'),
    array('file'=>'global/host_templates.cfg','unique'=>'name'),
    array('file'=>'global/misccommands.cfg','unique'=>'command_name'),
    array('file'=>'global/service_templates.cfg','unique'=>'name'),
  );

  echo 'Reconciling ' . count($files) . ' files...' . PHP_EOL;

  foreach ($files as $file) {
    $backup = '/tmp/nems_migrator_restore/etc/nagios3/' . $file['file'];
    $default = '/root/nems/nems-migrator/data/nagios/' . $file['file'];
    $dest = '/etc/nagios3/' . $file['file'];

    $data = new stdClass();
    $data->backup = parsefile($backup,$file);
    $data->default = parsefile($default,$file);

    if (isset($data->backup) && isset($data->default)) {
      $consolidation = array();
      # Load the defaults
      foreach ($data->default as $definition) {
        $consolidation[$definition['name']] = $definition['data'];
      }
      # Now overwrite defaults with NEMS-Migrator backup
      foreach ($data->backup as $definition) {
        if ($file == 'Default_collector/services.cfg' && isset($definition['name'])) {
          if (!isset($counter[$definition['name']])) $counter[$definition['name']] = 1; else $counter[$definition['name']] = $counter[$definition['name']]++;
          $definition['name'] = $definition['name'] . ' - ' . $counter[$definition['name']];
        }
        $consolidation[$definition['name']] = $definition['data'];
      }
      $newfile = '# ' . $file['file'] . PHP_EOL . '# This file was generated by NEMS-Migrate' . PHP_EOL . '# Visit http://baldnerd.com/nems/ to learn more' . PHP_EOL . PHP_EOL;
      foreach ($consolidation as $definition) {
        foreach ($definition as $index=>$line) {
          $newfile .= '          ';
          if ($index != 0 && $index != key( array_slice( $definition, -1, 1, TRUE ) ) ) $newfile .= '          '; // some basic indentation
          $newfile .= $line . PHP_EOL;
        }
        $newfile .= PHP_EOL;
      }
      // clobber the original file
      file_put_contents($dest,$newfile);
    }

  }


    echo 'Consolidation complete.';

  echo PHP_EOL;

    function parsefile($filename,$file) {
      if (file_exists($filename)) $data = file($filename);
      $inside = 0;
      $index = 0;

      foreach ($data as $line) {

        $line = trim($line);

        if (substr($line,0,6) == 'define') {
          $inside = 1;
        }

        if ($inside == 1 && substr($line,0,strlen($file['unique'])) == $file['unique']) {
          $name = trim( substr( $line,strlen($file['unique']) ) );
          $definitions[$index]['name'] = $name;
        }


        if ($inside == 1) $definitions[$index]['data'][] = $line;

        if (substr($line,0,1) == '}') {
          $inside = 0;
          $index++;
        }

      }
      return $definitions;
    }


?>
